[workspace]
members = [
  "rust/noosphere",
  "rust/noosphere-api",
  "rust/noosphere-car",
  "rust/noosphere-cli",
  "rust/noosphere-collections",
  "rust/noosphere-core",
  "rust/noosphere-gateway",
  "rust/noosphere-into",
  "rust/noosphere-ipfs",
  "rust/noosphere-ns",
  "rust/noosphere-sphere",
  "rust/noosphere-storage",
]

# See: https://github.com/rust-lang/rust/issues/90148#issuecomment-949194352
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1" }
subtext = { version = "0.3.4" }
tempfile = { version = "^3" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "~0.3.16", features = ["env-filter", "tracing-log"] }
thiserror = { version = "1" }
gloo-timers = { version = "0.2", features = ["futures"] }
ucan = { version = "0.3.0" }
ucan-key-support = { version = "0.1.4" }
libipld = { version = "0.16" }
libipld-core = { version = "0.16" }
libipld-cbor = { version = "0.16" }
cid = { version = "0.10" }
multihash = { version = "0.18" }
void = { version = "1" }
wnfs-namefilter = { version = "0.1.20" }
strum = { version = "0.24" }
strum_macros = { version = "0.24" }
serde = { version = "^1" }
serde_json = { version = "^1" }

js-sys = { version = "^0.3" }
wasm-bindgen = { version = "^0.2" }
wasm-bindgen-test = { version = "^0.3" }
wasm-bindgen-futures = { version = "^0.4" }

[profile.release]
opt-level = 'z'
lto = true

