[workspace]
members = [
  "rust/noosphere",
  "rust/noosphere-api",
  "rust/noosphere-car",
  "rust/noosphere-cli",
  "rust/noosphere-collections",
  "rust/noosphere-core",
  "rust/noosphere-gateway",
  "rust/noosphere-into",
  "rust/noosphere-ipfs",
  "rust/noosphere-ns",
  "rust/noosphere-sphere",
  "rust/noosphere-storage",
]

# See: https://github.com/rust-lang/rust/issues/90148#issuecomment-949194352
resolver = "2"

[workspace.dependencies]
subtext = { version = "0.3.4" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "tracing-log"] }
thiserror = { version = "1" }
instant = { version = "0.1" }
gloo-timers = { version = "0.2", features = ["futures"] }
ucan = { version = "0.1.2" }
ucan-key-support = { version = "0.1.2" }
libipld = { version = "0.16" }
libipld-core = { version = "0.16" }
libipld-cbor = { version = "0.16" }
cid = { version = "0.10" }
multihash = { version = "0.18" }
void = { version = "1.0.2" }
wnfs-namefilter = { version = "0.1.20" }

[profile.release]
opt-level = 'z'
lto = true

