[workspace]
members = [
  "rust/noosphere",
  "rust/noosphere-api",
  "rust/noosphere-car",
  "rust/noosphere-cli",
  "rust/noosphere-collections",
  "rust/noosphere-core",
  "rust/noosphere-gateway",
  "rust/noosphere-into",
  "rust/noosphere-ipfs",
  "rust/noosphere-ns",
  "rust/noosphere-sphere",
  "rust/noosphere-storage",
]

# See: https://github.com/rust-lang/rust/issues/90148#issuecomment-949194352
resolver = "2"

[workspace.dependencies]
subtext = { version = "0.3.4" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "~0.3", features = ["env-filter", "tracing-log"] }
thiserror = { version = "^1.0.38" }

[profile.release]
opt-level = 'z'
lto = true

