[package]
name = "noosphere-cbor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
serde = "^1"
serde_ipld_dagcbor = "~0.2"
