[package]
name = "noosphere-core"
version = "0.6.2"
edition = "2021"
description = "Core data types of the Rust Noosphere implementation"
keywords = ["hamt", "ipld", "noosphere", "p2p", "async"]
categories = [
  "data-structures",
  "asynchronous",
  "encoding",
  "web-programming",
  "web-assembly"
]
rust-version = "1.60.0"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/noosphere-core"
repository = "https://github.com/subconsciousnetwork/noosphere"
homepage = "https://github.com/subconsciousnetwork/noosphere"
readme = "README.md"

[dependencies]
log = "~0.4"
cid = "~0.9"
url = "^2"
async-trait = "~0.1"
async-recursion = "^1"
async-std = "^1"
async-stream = "~0.3"

# NOTE: async-once-cell 0.4.0 shipped unstable feature usage
async-once-cell = "~0.3"
anyhow = "^1"
fastcdc = "^1"
futures = "~0.3"
fvm_ipld_amt = "~0.5"
serde = "^1"
byteorder = "^1.4"
base64 = "~0.13"
ed25519-zebra = "^3"
rand = "~0.8"
once_cell = "^1"
serde_ipld_dagcbor = "~0.2"
tiny-bip39 = "^1"
crdts = "^7"
tokio-stream = "~0.1"
libipld-core = "~0.15"
libipld-cbor = "~0.15"

noosphere-storage = { version = "0.4.1", path = "../noosphere-storage" }
noosphere-collections = { version = "0.3.1", path = "../noosphere-collections" }

ucan = { version = "0.1.0" }
ucan-key-support = { version = "0.1.0" }

[dev-dependencies]
wasm-bindgen-test = "~0.3"
serde_bytes = "~0.11"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "^1", features = ["full"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# NOTE: This is needed so that rand can be included in WASM builds
getrandom = { version = "~0.2", features = ["js"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
tokio = { version = "^1", features = ["sync"] }