[workspace]
members = [
  "noosphere-cbor",
  "noosphere-storage",
  "noosphere-collections",
  "noosphere",
  "noosphere-api",
  "noosphere-fs",
  "noosphere-gateway",
  "noosphere-into"
]
# See: https://github.com/rust-lang/rust/issues/90148#issuecomment-949194352
resolver = "2"

