[package]
name = "noosphere-gateway"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ng"
path = "src/main.rs"

[dependencies]
tracing.workspace = true
anyhow.workspace = true

[dev-dependencies]
temp-dir.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ucan.workspace = true
ucan-key-support.workspace = true

cid.workspace = true

noosphere = { path = "../noosphere" }
noosphere-api = { path = "../noosphere-api" }
noosphere-storage = { path = "../noosphere-storage" }
noosphere-cbor = { path = "../noosphere-cbor" }
noosphere-collections = { path = "../noosphere-collections" }

zeroize = "^1"
sha2.workspace = true
rand.workspace = true
url.workspace = true
jsonwebtoken = "^8"
# base64 = "0.13"
# ed25519-zebra = "^3"

mime = "~0.3"
tokio = { workspace = true, features = ["full"] }
tower = "~0.4"
tower-http = { version = "~0.3", features = ["cors", "trace"] }
tracing-subscriber.workspace = true
axum = { version = "~0.5.16", features = ["headers", "macros"] }
hyper = { version = "~0.14", features = ["client"] }
sled.workspace = true
toml_edit = "~0.14"
async-std.workspace = true
async-once-cell.workspace = true
async-trait.workspace = true
futures.workspace = true

clap = { version = "^3", features = ["derive"] }
pretty_env_logger = "~0.4"
serde_json = "^1"
serde.workspace = true