[package]
name = "noosphere-gateway"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ng"
path = "src/main.rs"

[dependencies]
tracing = "0.1"
anyhow = "^1"

[dev-dependencies]
temp-dir = "0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ucan = { version = "0.7.0-alpha.1" }
ucan-key-support = { version = "0.7.0-alpha.1" }
cid = "0.8"

noosphere = { path = "../noosphere" }
noosphere-api = { path = "../noosphere-api" }
noosphere-storage = { path = "../noosphere-storage" }
noosphere-cbor = { path = "../noosphere-cbor" }
noosphere-collections = { path = "../noosphere-collections" }

zeroize = "^1"
sha2 = "~0.10"
rand = "~0.8"
url = "^2"
jsonwebtoken = "^8"
# base64 = "0.13"
# ed25519-zebra = "^3"

mime = "~0.3"
tokio = { version = "^1", features = ["full"] }
tower = "~0.4"
tower-http = { version = "~0.3", features = ["cors", "trace"] }
tracing-subscriber = { version = "~0.3", features = ["env-filter"] }
# 
axum = { version = "~0.5.16", features = ["headers", "macros"] }
hyper = { version = "~0.14", features = ["client"] }
sled = "~0.34"
toml_edit = "~0.14"
async-std = "^1"
async-once-cell = "~0.3"
async-trait = "~0.1"
futures = "~0.3"

clap = { version = "^3", features = ["derive"] }
pretty_env_logger = "~0.4"
serde_json = "^1"
serde = "^1"
serde_bytes = "~0.11"

libipld-core = "~0.14"
libipld-cbor = "~0.14"