[package]
name = "noosphere-gateway"
version = "0.7.2"
edition = "2021"
description = "A geist on the network that enables user spheres to discover each other"
keywords = ["http", "geist", "noosphere", "p2p", "ucan"]
categories = [
  "network-programming",
  "asynchronous",
]
rust-version = "1.60.0"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/noosphere-gateway"
repository = "https://github.com/subconsciousnetwork/noosphere"
homepage = "https://github.com/subconsciousnetwork/noosphere"
readme = "README.md"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
reqwest = { version = "~0.11", default-features = false, features = ["json", "rustls-tls", "stream"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow = "^1"
iroh-car = { workspace = true }
thiserror = { workspace = true }
strum = "0.24"
strum_macros = "0.24"
bytes = "^1"

tokio = { version = "^1", features = ["full"] }
tokio-stream = "~0.1"
axum = { version = "0.6.11", features = ["headers", "macros"] }
tower = "~0.4"
tower-http = { version = "~0.3", features = ["cors", "trace"] }
async-trait = "~0.1"
async-stream = "~0.3"
tracing = { workspace = true }
wnfs-namefilter = { version = "0.1.21" }

url = { version = "^2", features = [ "serde" ] }
mime_guess = "^2"

noosphere-ipfs = { version = "0.7.1", path = "../noosphere-ipfs" }
noosphere-core = { version = "0.14.0", path = "../noosphere-core" }
noosphere-ns = { version = "0.9.4", path = "../noosphere-ns" }
noosphere-storage = { version = "0.7.1", path = "../noosphere-storage" }
noosphere-sphere = { version = "0.9.0", path = "../noosphere-sphere" }
noosphere-api = { version = "0.11.0", path = "../noosphere-api" }
ucan = { workspace = true }
ucan-key-support = { workspace = true }
cid = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
libipld-core = { workspace = true }
libipld-cbor = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }

