[package]
name = "noosphere-gateway"
version = "0.2.0"
edition = "2021"
description = "A geist on the network that enables user spheres to discover each other"
keywords = ["http", "geist", "noosphere", "p2p", "ucan"]
categories = [
  "network-programming",
  "asynchronous",
]
rust-version = "1.60.0"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/noosphere-gateway"
repository = "https://github.com/subconsciousnetwork/noosphere"
homepage = "https://github.com/subconsciousnetwork/noosphere"
readme = "README.md"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
reqwest = { version = "~0.11", default-features = false, features = ["json", "rustls-tls", "stream"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tempfile = "^3"
clap = { version = "^4", features = ["derive", "cargo"] }
anyhow = "^1"
thiserror = "1.0.38"
strum = "0.24"
strum_macros = "0.24"
bytes = "^1"

tokio = { version = "^1", features = ["full"] }
tokio-stream = "~0.1"
axum = { version = "0.6.11", features = ["headers", "macros"] }
tower = "~0.4"
tower-http = { version = "~0.3", features = ["cors", "trace"] }
async-trait = "~0.1"
async-stream = "~0.3"
tracing = { workspace = true }
multipart = "~0.18"
wnfs-namefilter = { version = "0.1.19" }

url = { version = "^2", features = [ "serde" ] }
whoami = "^1"
home = "~0.5"
pathdiff = "~0.2"
path-absolutize = "^3"
mime_guess = "^2"
witty-phrase-generator = "~0.2"
toml_edit = { version = "~0.15", features = [ "serde" ] }
globset = "~0.4"

noosphere-car = { version = "0.1.0", path = "../noosphere-car" }
noosphere-ipfs = { version = "0.3.0", path = "../noosphere-ipfs" }
noosphere-core = { version = "0.8.0", path = "../noosphere-core" }
noosphere-ns = { version = "0.5.1", path = "../noosphere-ns" }
noosphere-storage = { version = "0.6.0", path = "../noosphere-storage" }
noosphere-sphere = { version = "0.2.0", path = "../noosphere-sphere" }
noosphere-api = { version = "0.7.0", path = "../noosphere-api" }
noosphere = { version = "0.8.0", path = "../noosphere" }
ucan = { version = "0.1.0" }
ucan-key-support = { version = "0.1.0" }
cid = "~0.9"
subtext = "0.3.2"

serde = "^1"
serde_json = "^1"
libipld-core = "~0.15"
libipld-cbor = "~0.15"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "~0.2"

