[package]
name = "noosphere-into"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noosphere = { path = "../noosphere" }
noosphere-storage = { path = "../noosphere-storage" }
noosphere-fs = { path = "../noosphere-fs" }
subtext = { version = "~0.3", features = ["stream"] }

anyhow.workspace = true
async-trait.workspace = true

horrorshow = "~0.8"
cid.workspace = true

bytes.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tokio = { workspace = true, features = ["macros", "test-util"] }

async-stream.workspace = true
futures.workspace = true
async-compat = { version = "~0.2" }
async-utf8-decoder = { version = "~0.3" }

[dev-dependencies]
wasm-bindgen-test.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
# Mostly these dependencies are used in the examples
tokio = { workspace = true, features = ["full"] }
temp-dir.workspace = true
axum = "~0.5"
axum-extra = { version = "~0.3", features = ["spa"] }
tower-http = { version = "~0.3", features = ["fs", "trace"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ucan.workspace = true
ucan-key-support.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
ucan = { workspace = true, features = ["web"] }
ucan-key-support = { workspace = true, features = ["web"] }