[package]
name = "noosphere-into"
version = "0.8.1"
edition = "2021"
description = "Transformations of Noosphere content into various target formats"
keywords = ["html", "ipld", "noosphere", "subtext", "transcode"]
categories = [
  "asynchronous",
  "web-programming",
  "file-system"
]
rust-version = "1.60.0"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/noosphere-into"
repository = "https://github.com/subconsciousnetwork/noosphere"
homepage = "https://github.com/subconsciousnetwork/noosphere"
readme = "README.md"

[dependencies]
noosphere-core = { version = "0.10.1", path = "../noosphere-core" }
noosphere-storage = { version = "0.6.2", path = "../noosphere-storage" }
noosphere-sphere = { version = "0.5.1", path = "../noosphere-sphere" }
subtext = { version = "0.3.2", features = ["stream"] }
async-trait = "~0.1"
url = "2"
tracing = { workspace = true }

anyhow = "^1"

horrorshow = "~0.8"
cid = { workspace = true }
libipld-cbor = { workspace = true }

bytes = "^1"
tokio-stream = "~0.1"
tokio-util = "~0.7"
tokio = { version = "^1", features = ["io-util", "macros", "test-util"] }

async-stream = { version = "~0.3" }
futures = { version = "~0.3" }
async-compat = { version = "~0.2" }
async-utf8-decoder = { version = "~0.3" }

ucan = { workspace = true }
ucan-key-support = { workspace = true }

[dev-dependencies]
noosphere-sphere = { version = "0.5.1", path = "../noosphere-sphere", features = ["helpers"] }
wasm-bindgen-test = "~0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
# Mostly these dependencies are used in the examples
tokio = { version = "^1", features = ["full"] }
tempfile = "^3"
axum = "~0.6"
axum-extra = { version = "~0.4", features = ["spa"] }
tower-http = { version = "~0.3", features = ["fs", "trace"] }
