[package]
name = "noosphere-into"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noosphere = { path = "../noosphere" }
noosphere-storage = { path = "../noosphere-storage" }
noosphere-fs = { path = "../noosphere-fs" }
subtext = { version = "~0.3", features = ["stream"] }

anyhow = "^1"
async-trait = "~0.1"

horrorshow = "~0.8"
cid = "~0.8"

bytes = "^1"
tokio-stream = "~0.1"
tokio-util = "~0.7"
tokio = { version = "^1", features = ["io-util", "macros", "test-util"] }

async-stream = { version = "~0.3" }
futures = { version = "~0.3" }
async-compat = { version = "~0.2" }
async-utf8-decoder = { version = "~0.3" }

ucan = { version = "0.6.0-alpha.1", git = "https://github.com/cdata/rs-ucan.git", branch = "feature/canonicalization" }
ucan-key-support = { version = "0.4.0-alpha.1", git = "https://github.com/cdata/rs-ucan.git", branch = "feature/canonicalization" }



[dev-dependencies]
wasm-bindgen-test = "~0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
# Mostly these dependencies are used in the examples
tokio = { version = "^1", features = ["full"] }
temp-dir = "~0.1"
axum = "~0.5"
axum-extra = { version = "~0.3", features = ["spa"] }
tower-http = { version = "~0.3", features = ["fs", "trace"] }
tracing = "~0.1"
tracing-subscriber = { version = "~0.3", features = ["env-filter"] }
